package main

import (
	"database/sql"
	"regexp"
	"sort"
	"strings"
)

// TYPE export with metadata-driven approach

func loadTypes(db *sql.DB) ([]*TypeDef, error) {
	types := map[string]*TypeDef{}

	// Query to get all TYPE objects from user_objects
	rows, err := db.Query(`
SELECT DISTINCT object_name
FROM user_objects
WHERE object_type = 'TYPE'
  AND generated = 'N'
ORDER BY object_name`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		types[name] = &TypeDef{Name: name, Owner: ""}
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	// For each type, extract the field definitions from user_source
	for typeName, typeDef := range types {
		fields, err := loadTypeFields(db, typeName)
		if err != nil {
			return nil, err
		}
		typeDef.Fields = fields
	}

	list := make([]*TypeDef, 0, len(types))
	for _, t := range types {
		list = append(list, t)
	}
	sort.Slice(list, func(i, j int) bool { return list[i].Name < list[j].Name })
	return list, nil
}

func loadTypeFields(db *sql.DB, typeName string) ([]*TypeField, error) {
	rows, err := db.Query(`
SELECT text
FROM user_source
WHERE name = :1 AND (type = 'TYPE' OR type = 'TYPE BODY')
ORDER BY line`, typeName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var source strings.Builder
	for rows.Next() {
		var line string
		if err := rows.Scan(&line); err != nil {
			return nil, err
		}
		source.WriteString(line)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return parseTypeSource(source.String(), typeName)
}

func parseTypeSource(source, typeName string) ([]*TypeField, error) {
	fields := []*TypeField{}

	// Normalize whitespace for regex matching
	normalized := normalizeWhitespace(source)

	// Handle TABLE OF type (nested table)
	tableOfRe := regexp.MustCompile(`(?i)TYPE\s+` + regexp.QuoteMeta(typeName) + `\s+(?:AS|IS)\s+TABLE\s+OF\s+(.+?)\s*;`)
	if tableOfMatch := tableOfRe.FindStringSubmatch(normalized); len(tableOfMatch) > 1 {
		typeOf := strings.TrimSpace(tableOfMatch[1])
		typeOf = strings.ToLower(typeOf)
		// Remove any trailing semicolon or parentheses
		typeOf = strings.TrimSuffix(typeOf, ";")
		typeOf = strings.TrimSpace(typeOf)
		// Preserve length specification for varchar types
		mappedType := mapOracleToPgTypeWithLength(typeOf)
		fields = append(fields, &TypeField{
			Name:     strings.ToLower(typeName),
			DataType: mappedType + "[]",
		})
		return fields, nil
	}

	// Handle OBJECT type (composite type with fields)
	objRe := regexp.MustCompile(`(?i)TYPE\s+` + regexp.QuoteMeta(typeName) + `\s+(?:AS|IS)\s+OBJECT\s*\((.*?)\)\s*;`)
	objMatch := objRe.FindStringSubmatch(normalized)
	if len(objMatch) > 1 {
		fieldDefs := objMatch[1]
		// Parse comma-separated field definitions
		parts := strings.Split(fieldDefs, ",")
		for _, part := range parts {
			part = strings.TrimSpace(part)
			if part == "" {
				continue
			}
			// Split field name from type
			tokens := strings.Fields(part)
			if len(tokens) < 2 {
				continue
			}
			fieldName := strings.ToLower(tokens[0])
			fieldType := strings.Join(tokens[1:], " ")
			fieldType = strings.TrimSpace(fieldType)
			fieldType = strings.ToLower(fieldType)
			// Map Oracle type to PG, preserving length specifications
			fieldType = mapOracleToPgTypeWithLength(fieldType)
			fields = append(fields, &TypeField{
				Name:     fieldName,
				DataType: fieldType,
			})
		}
		return fields, nil
	}

	return fields, nil
}

func renderTypes(types []*TypeDef) string {
	var b strings.Builder
	b.WriteString("-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0\n")
	b.WriteString("-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.\n")
	b.WriteString("-- DATASOURCE: dbi:Oracle:host=oracle;port=1521;service_name=XEPDB1\n\n")
	b.WriteString("SET client_encoding TO 'UTF8';\n\n")
	b.WriteString("SET search_path = app,public;\n")
	b.WriteString("\\set ON_ERROR_STOP ON\n\n")
	b.WriteString("SET check_function_bodies = false;\n\n")
	b.WriteString("CREATE SCHEMA IF NOT EXISTS app;\n")

	for i, t := range types {
		if len(t.Fields) == 1 && strings.HasSuffix(t.Fields[0].DataType, "[]") {
			// TABLE OF type (nested table)
			elementType := strings.TrimSuffix(t.Fields[0].DataType, "[]")
			b.WriteString("CREATE TYPE ")
			b.WriteString(strings.ToLower(t.Name))
			b.WriteString(" AS (")
			b.WriteString(strings.ToLower(t.Name))
			b.WriteString(" ")
			b.WriteString(elementType)
			b.WriteString("[]);\n")
		} else {
			// OBJECT type (composite type)
			b.WriteString("CREATE TYPE ")
			b.WriteString(strings.ToLower(t.Name))
			b.WriteString(" AS (\n")

			// Calculate max field name length for alignment
			maxNameLen := 0
			for _, f := range t.Fields {
				if len(f.Name) > maxNameLen {
					maxNameLen = len(f.Name)
				}
			}

			for j, f := range t.Fields {
				if j > 0 {
					b.WriteString("\t")
				}
				b.WriteString(f.Name)
				// Add spaces to align type values
				padding := maxNameLen - len(f.Name)
				b.WriteString(strings.Repeat(" ", padding+1))
				b.WriteString(f.DataType)
				if j < len(t.Fields)-1 {
					b.WriteString(",\n")
				} else {
					b.WriteString("\n\n")
				}
			}
			b.WriteString(");\n")
		}
		if i < len(types)-1 {
			b.WriteString("\n")
		}
	}

	b.WriteString("\n")
	return b.String()
}
